<?php

namespace Proxies\__CG__\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Registros extends \Entities\Registros implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Entities\\Registros' . "\0" . 'id', '' . "\0" . 'Entities\\Registros' . "\0" . 'empresa', '' . "\0" . 'Entities\\Registros' . "\0" . 'numempleados', '' . "\0" . 'Entities\\Registros' . "\0" . 'sector', '' . "\0" . 'Entities\\Registros' . "\0" . 'telefono', '' . "\0" . 'Entities\\Registros' . "\0" . 'movil', '' . "\0" . 'Entities\\Registros' . "\0" . 'administrador', '' . "\0" . 'Entities\\Registros' . "\0" . 'percontacto', '' . "\0" . 'Entities\\Registros' . "\0" . 'cif', '' . "\0" . 'Entities\\Registros' . "\0" . 'direccion', '' . "\0" . 'Entities\\Registros' . "\0" . 'cp', '' . "\0" . 'Entities\\Registros' . "\0" . 'provincia', '' . "\0" . 'Entities\\Registros' . "\0" . 'poblacion', '' . "\0" . 'Entities\\Registros' . "\0" . 'web', '' . "\0" . 'Entities\\Registros' . "\0" . 'email', '' . "\0" . 'Entities\\Registros' . "\0" . 'comentario', '' . "\0" . 'Entities\\Registros' . "\0" . 'fregistro', '' . "\0" . 'Entities\\Registros' . "\0" . 'tregistro', '' . "\0" . 'Entities\\Registros' . "\0" . 'oculto', '' . "\0" . 'Entities\\Registros' . "\0" . 'lineasmovil', '' . "\0" . 'Entities\\Registros' . "\0" . 'lineasdatos', '' . "\0" . 'Entities\\Registros' . "\0" . 'adsl', '' . "\0" . 'Entities\\Registros' . "\0" . 'conectapymes', '' . "\0" . 'Entities\\Registros' . "\0" . 'centralita', '' . "\0" . 'Entities\\Registros' . "\0" . 'centralitas', '' . "\0" . 'Entities\\Registros' . "\0" . 'tipocpyme', '' . "\0" . 'Entities\\Registros' . "\0" . 'permanencia', '' . "\0" . 'Entities\\Registros' . "\0" . 'tpermanencia', '' . "\0" . 'Entities\\Registros' . "\0" . 'idestado', '' . "\0" . 'Entities\\Registros' . "\0" . 'idusuario', '' . "\0" . 'Entities\\Registros' . "\0" . 'idoperador'];
        }

        return ['__isInitialized__', '' . "\0" . 'Entities\\Registros' . "\0" . 'id', '' . "\0" . 'Entities\\Registros' . "\0" . 'empresa', '' . "\0" . 'Entities\\Registros' . "\0" . 'numempleados', '' . "\0" . 'Entities\\Registros' . "\0" . 'sector', '' . "\0" . 'Entities\\Registros' . "\0" . 'telefono', '' . "\0" . 'Entities\\Registros' . "\0" . 'movil', '' . "\0" . 'Entities\\Registros' . "\0" . 'administrador', '' . "\0" . 'Entities\\Registros' . "\0" . 'percontacto', '' . "\0" . 'Entities\\Registros' . "\0" . 'cif', '' . "\0" . 'Entities\\Registros' . "\0" . 'direccion', '' . "\0" . 'Entities\\Registros' . "\0" . 'cp', '' . "\0" . 'Entities\\Registros' . "\0" . 'provincia', '' . "\0" . 'Entities\\Registros' . "\0" . 'poblacion', '' . "\0" . 'Entities\\Registros' . "\0" . 'web', '' . "\0" . 'Entities\\Registros' . "\0" . 'email', '' . "\0" . 'Entities\\Registros' . "\0" . 'comentario', '' . "\0" . 'Entities\\Registros' . "\0" . 'fregistro', '' . "\0" . 'Entities\\Registros' . "\0" . 'tregistro', '' . "\0" . 'Entities\\Registros' . "\0" . 'oculto', '' . "\0" . 'Entities\\Registros' . "\0" . 'lineasmovil', '' . "\0" . 'Entities\\Registros' . "\0" . 'lineasdatos', '' . "\0" . 'Entities\\Registros' . "\0" . 'adsl', '' . "\0" . 'Entities\\Registros' . "\0" . 'conectapymes', '' . "\0" . 'Entities\\Registros' . "\0" . 'centralita', '' . "\0" . 'Entities\\Registros' . "\0" . 'centralitas', '' . "\0" . 'Entities\\Registros' . "\0" . 'tipocpyme', '' . "\0" . 'Entities\\Registros' . "\0" . 'permanencia', '' . "\0" . 'Entities\\Registros' . "\0" . 'tpermanencia', '' . "\0" . 'Entities\\Registros' . "\0" . 'idestado', '' . "\0" . 'Entities\\Registros' . "\0" . 'idusuario', '' . "\0" . 'Entities\\Registros' . "\0" . 'idoperador'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Registros $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresa($empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresa', [$empresa]);

        return parent::setEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', []);

        return parent::getEmpresa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumempleados($numempleados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumempleados', [$numempleados]);

        return parent::setNumempleados($numempleados);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumempleados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumempleados', []);

        return parent::getNumempleados();
    }

    /**
     * {@inheritDoc}
     */
    public function setSector($sector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSector', [$sector]);

        return parent::setSector($sector);
    }

    /**
     * {@inheritDoc}
     */
    public function getSector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSector', []);

        return parent::getSector();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setMovil($movil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovil', [$movil]);

        return parent::setMovil($movil);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovil', []);

        return parent::getMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdministrador($administrador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdministrador', [$administrador]);

        return parent::setAdministrador($administrador);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdministrador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdministrador', []);

        return parent::getAdministrador();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercontacto($percontacto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercontacto', [$percontacto]);

        return parent::setPercontacto($percontacto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercontacto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercontacto', []);

        return parent::getPercontacto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCif($cif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCif', [$cif]);

        return parent::setCif($cif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCif', []);

        return parent::getCif();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', [$cp]);

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', []);

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvincia($provincia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvincia', [$provincia]);

        return parent::setProvincia($provincia);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvincia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvincia', []);

        return parent::getProvincia();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoblacion($poblacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoblacion', [$poblacion]);

        return parent::setPoblacion($poblacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoblacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoblacion', []);

        return parent::getPoblacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeb($web)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeb', [$web]);

        return parent::setWeb($web);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeb', []);

        return parent::getWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setComentario($comentario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComentario', [$comentario]);

        return parent::setComentario($comentario);
    }

    /**
     * {@inheritDoc}
     */
    public function getComentario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComentario', []);

        return parent::getComentario();
    }

    /**
     * {@inheritDoc}
     */
    public function setFregistro($fregistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFregistro', [$fregistro]);

        return parent::setFregistro($fregistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getFregistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFregistro', []);

        return parent::getFregistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setTregistro($tregistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTregistro', [$tregistro]);

        return parent::setTregistro($tregistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getTregistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTregistro', []);

        return parent::getTregistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setOculto($oculto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOculto', [$oculto]);

        return parent::setOculto($oculto);
    }

    /**
     * {@inheritDoc}
     */
    public function getOculto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOculto', []);

        return parent::getOculto();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineasmovil($lineasmovil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineasmovil', [$lineasmovil]);

        return parent::setLineasmovil($lineasmovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineasmovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineasmovil', []);

        return parent::getLineasmovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setLineasdatos($lineasdatos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLineasdatos', [$lineasdatos]);

        return parent::setLineasdatos($lineasdatos);
    }

    /**
     * {@inheritDoc}
     */
    public function getLineasdatos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLineasdatos', []);

        return parent::getLineasdatos();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdsl($adsl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdsl', [$adsl]);

        return parent::setAdsl($adsl);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdsl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdsl', []);

        return parent::getAdsl();
    }

    /**
     * {@inheritDoc}
     */
    public function setConectapymes($conectapymes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConectapymes', [$conectapymes]);

        return parent::setConectapymes($conectapymes);
    }

    /**
     * {@inheritDoc}
     */
    public function getConectapymes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConectapymes', []);

        return parent::getConectapymes();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentralita($centralita)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentralita', [$centralita]);

        return parent::setCentralita($centralita);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentralita()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentralita', []);

        return parent::getCentralita();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentralitas($centralitas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentralitas', [$centralitas]);

        return parent::setCentralitas($centralitas);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentralitas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentralitas', []);

        return parent::getCentralitas();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipocpyme($tipocpyme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipocpyme', [$tipocpyme]);

        return parent::setTipocpyme($tipocpyme);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipocpyme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipocpyme', []);

        return parent::getTipocpyme();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermanencia($permanencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermanencia', [$permanencia]);

        return parent::setPermanencia($permanencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermanencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermanencia', []);

        return parent::getPermanencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setTpermanencia($tpermanencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpermanencia', [$tpermanencia]);

        return parent::setTpermanencia($tpermanencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getTpermanencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpermanencia', []);

        return parent::getTpermanencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdoperador($idoperador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdoperador', [$idoperador]);

        return parent::setIdoperador($idoperador);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdoperador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdoperador', []);

        return parent::getIdoperador();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdestado($idestado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdestado', [$idestado]);

        return parent::setIdestado($idestado);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdestado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdestado', []);

        return parent::getIdestado();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdusuario($idusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdusuario', [$idusuario]);

        return parent::setIdusuario($idusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdusuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdusuario', []);

        return parent::getIdusuario();
    }

}
